# Generated by Django 2.1.5 on 2020-06-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='datetime',
            new_name='time',
        ),
    ]
