# Generated by Django 2.1.5 on 2020-06-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_contactus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
