# Generated by Django 2.2.9 on 2024-03-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('website', models.URLField(max_length=250)),
                ('designer', models.CharField(blank=True, max_length=50)),
                ('developer', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='aboutus')),
                ('background_img', models.ImageField(blank=True, null=True, upload_to='aboutus')),
                ('screenshoot', models.ImageField(blank=True, null=True, upload_to='aboutus')),
                ('address1', models.CharField(blank=True, max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250)),
                ('address3', models.CharField(blank=True, max_length=250)),
                ('address4', models.CharField(blank=True, max_length=250)),
                ('address5', models.CharField(blank=True, max_length=250)),
                ('email1', models.EmailField(blank=True, max_length=100)),
                ('email2', models.EmailField(blank=True, max_length=100)),
                ('email3', models.EmailField(blank=True, max_length=100)),
                ('mobile1', models.CharField(blank=True, max_length=13)),
                ('mobile2', models.CharField(blank=True, max_length=13)),
                ('mobile3', models.CharField(blank=True, max_length=13)),
                ('bio', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True, max_length=10000)),
                ('mision', models.TextField(blank=True, max_length=10000)),
            ],
        ),
    ]
