# Generated by Django 2.1.5 on 2020-05-28 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('package_name', models.CharField(max_length=100)),
                ('title_activity_home', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='splash_screen')),
                ('splash_screen', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('email', models.EmailField(max_length=254)),
                ('website_url', models.CharField(max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
