# Generated by Django 2.2.9 on 2024-03-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Createapk', '0004_auto_20200615_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apkinfo',
            name='website_url',
            field=models.URLField(max_length=500),
        ),
    ]
